name: koopman-ocean
channels:
  - defaults
  - conda-forge
dependencies:
    - python=3.10.13
    - pip:
      - seaborn==0.13.2
      - isoduration==20.11.0
      - fqdn==1.5.1
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - certifi==2025.1.31
      - nest_asyncio==1.6.0
      - pyFFTW==0.15.0
      - prometheus_client==0.21.1
      - executing==2.2.0
      - yarl==1.18.3
      - PyYAML==6.0.2
      - Brotli==1.1.0
      - fonttools==4.55.8
      - pyzmq==24.0.1
      - pure_eval==0.2.3
      - numpy==1.26.4
      - frozenlist==1.5.0
      - safetensors==0.5.2
      - stack_data==0.6.3
      - google-auth-oauthlib==1.2.1
      - jupyterlab_server==2.27.3
      - packaging==24.2
      - nvidia-cusolver-cu12==11.6.1.9
      - typing_extensions==4.12.2
      - jupyter_core==5.7.2
      - scikit-learn==1.6.1
      - scikit-image==0.25.2
      - propcache==0.2.1
      - requests==2.32.3
      - cached-property==1.5.2
      - cmocean==4.0.3
      - traitlets==5.14.3
      - jsonpointer==3.0.0
      - terminado==0.18.1
      - platformdirs==4.3.6
      - cycler==0.12.1
      - tqdm==4.67.1
      - wandb==0.19.10
      - pillow==11.1.0
      - transformers==4.48.3
      - pyparsing==3.2.1
      - rsa==4.9
      - setuptools==77.0.3
      - jupyter_client==7.4.9
      - gitdb==4.0.12
      - types-python-dateutil==2.9.0.20241206
      - nbconvert==7.16.6
      # - pyqg_parameterization_benchmarks==0.0.1
      - oauthlib==3.2.2
      - nvidia-cublas-cu12==12.4.5.8
      - netCDF4==1.7.2
      - mypy==1.15.0
      - sniffio==1.3.1
      - greenlet==3.2.1
      - jupyter_server==2.15.0
      - cachetools==5.5.2
      - timm==1.0.15
      - rfc3986-validator==0.1.1
      - pyproj==3.7.0
      - hyperframe==6.1.0
      - bleach==6.2.0
      - typing_utils==0.1.0
      - nvidia-nvtx-cu12==12.4.127
      - sqlalchemy-stubs==0.4
      - torchvision==0.21.0
      - jupyterlab==4.3.5
      - pydantic_core==2.33.2
      - defusedxml==0.7.1
      - Cartopy==0.23.0
      - click==8.1.8
      - tokenizers==0.21.0
      - mpmath==1.3.0
      - asttokens==3.0.0
      - pre_commit==4.2.0
      - threadpoolctl==3.6.0
      - Pygments==2.19.1
      - mypy_extensions==1.1.0
      - jedi==0.19.2
      - pyasn1==0.6.1
      - nbclient==0.10.2
      - dask==2024.2.1
      - cftime==1.5.1.1
      - jupyter==1.1.1
      - fastrlock==0.8.3
      - nvidia-cuda-cupti-cu12==12.4.127
      - fasteners==0.19
      - jupyter-console==6.6.3
      - pexpect==4.9.0
      - setproctitle==1.3.6
      - jupyter_server_terminals==0.5.3
      - jupyterlab_widgets==3.0.13
      - jupyter-lsp==2.2.5
      - rpds-py==0.23.1
      - xarray==2025.3.0
      - h5netcdf==1.5.0
      - tensordict==0.8.1
      - pytz==2025.1
      - prompt_toolkit==3.0.50
      - distlib==0.3.9
      - toolz==1.0.0
      - multidict==6.1.0
      - python-json-logger==2.0.7
      - webcolors==24.11.1
      - tzdata==2025.1
      - google-api-core==2.24.1
      - hpack==4.1.0
      - importlib_metadata==8.6.1
      - swin-transformer-pytorch==0.4.1
      - async-lru==2.0.4
      - nvidia-nvjitlink-cu12==12.4.127
      - smmap==5.0.2
      - nvidia-cusparselt-cu12==0.6.2
      - gplearn==0.4.2
      - parso==0.8.4
      - sentry-sdk==2.27.0
      - pkgutil_resolve_name==1.3.10
      - scipy==1.15.2
      - huggingface-hub==0.28.1
      - numcodecs==0.13.1
      - cloudpickle==3.1.1
      - GitPython==3.1.44
      - ffmpeg==1.4
      - google-crc32c==1.6.0
      - networkx==3.4.2
      - debugpy==1.8.12
      - zarr==2.18.3
      - annotated-types==0.7.0
      - httpcore==1.0.7
      - Jinja2==3.1.5
      - aiohttp==3.9.3
      - pandas==2.2.1
      - zipp==3.21.0
      - numba==0.61.0
      - Send2Trash==1.8.3
      - googleapis-common-protos==1.68.0
      - h11==0.14.0
      - nvidia-cuda-runtime-cu12==12.4.127
      - Pebble==5.1.1
      - webencodings==0.5.1
      - entrypoints==0.4
      - pycparser==2.22
      - qgs==0.2.8
      - kiwisolver==1.4.8
      - idna==3.10
      - requests-oauthlib==2.0.0
      - google-resumable-media==2.7.2
      - jsonschema-specifications==2024.10.1
      - psutil==6.1.1
      - typing-inspection==0.4.0
      - ruff==0.11.8
      - contourpy==1.3.1
      - regex==2024.11.6
      - websocket-client==1.8.0
      - einops==0.8.0
      - nc-time-axis==1.4.1
      - locket==1.0.0
      - SQLAlchemy==2.0.40
      - fsspec==2025.2.0
      - llvmlite==0.44.0
      - nvidia-curand-cu12==10.3.5.147
      - pyshp==2.3.1
      - proto-plus==1.26.0
      - mistune==3.1.2
      - protobuf==5.29.3
      - partd==1.4.2
      - nbformat==5.10.4
      - nvidia-cusparse-cu12==12.3.1.170
      - identify==2.6.10
      - aiosignal==1.3.2
      - google-auth==2.38.0
      - Cython==3.0.12
      - MarkupSafe==3.0.2
      - matplotlib-inline==0.1.7
      - nvidia-cudnn-cu12==9.1.0.70
      - zstandard==0.23.0
      - PySocks==1.7.1
      - pickleshare==0.7.5
      - comm==0.2.2
      - decorator==5.1.1
      - six==1.17.0
      - asciitree==0.3.3
      - sparse==0.15.5
      - nvidia-cufft-cu12==11.2.1.3
      - jupyterlab_pygments==0.3.0
      - anyio==4.8.0
      - filelock==3.17.0
      - widgetsnbextension==4.0.13
      - triton==3.2.0
      - ipywidgets==8.1.2
      - notebook==7.3.2
      - nvidia-nccl-cu12==2.21.5
      - python-dateutil==2.9.0.post0
      - pandocfilters==1.5.0
      - sympy==1.13.1
      - urllib3==2.3.0
      - orjson==3.10.18
      - notebook_shim==0.2.4
      - soupsieve==2.5
      - arrow==1.3.0
      - joblib==1.4.2
      - ipykernel==6.29.5
      - matplotlib==3.10.1
      - virtualenv==20.30.0
      - torch==2.6.0
      # - pyqg==0.7.2
      - argon2-cffi==23.1.0
      - tornado==6.4.2
      - pip==25.1
      - cffi==1.17.1
      - attrs==25.1.0
      - nodeenv==1.9.1
      - shapely==2.0.7
      - rfc3339_validator==0.1.4
      - json5==0.10.0
      - importlib_resources==6.5.2
      - h2==4.2.0
      - google-cloud-storage==3.1.0
      - wheel==0.45.1
      - charset-normalizer==3.4.1
      - httpx==0.28.1
      - uri-template==1.3.0
      - argon2-cffi-bindings==21.2.0
      - google-cloud-core==2.4.2
      - tomli==2.2.1
      - beautifulsoup4==4.13.3
      - async-timeout==4.0.3
      - ptyprocess==0.7.0
      - wcwidth==0.2.13
      - tinycss2==1.4.0
      - cupy-cuda12x==13.4.0
      - h5py==3.13.0
      - xarrayutils==2.0.1
      - fastjsonschema==2.21.1
      - ipython==8.32.0
      - gcsfs==2025.2.0
      - pydantic==2.11.4
      - cfgv==3.4.0
      - exceptiongroup==1.2.2
      - jsonschema==4.23.0
      - referencing==0.36.2
      - docker-pycreds==0.4.0
      - babel==2.17.0
      - jupyter-events==0.12.0
      - overrides==7.7.0
      - pyasn1_modules==0.4.1
      - pre-commit==4.2.0
      - torchtyping==0.1.5
