evaluations:
  - name: "continous_linear_1024"
    model_type: kae
    config_path: "experiment/continous_linear_1024.yaml"
    checkpoint_path: "/home/rg625/mnt/ocean_forecasting/koopman_autoencoder/model_outputs/continous_linear_1024/dummy-0q042lfv/checkpoints/epoch_1000.pth"
  - name: ACDM
    model_type: acdm
    checkpoint_path: /home/rg625/mnt/ocean_forecasting/autoreg_pde_diffusion/pretrained_models/models_inc/128_acdm-r20_00/Model.pth
    # checkpoint_path: /home/rg625/mnt/ocean_forecasting/autoreg_pde_diffusion/pretrained_models/models_inc/128_acdm-r20_02/Model.pth
  - name: ACDM_ncn
    model_type: acdm_ncn
    checkpoint_path: /home/rg625/mnt/ocean_forecasting/autoreg_pde_diffusion/pretrained_models/models_inc/128_acdm-r20_ncn_00/Model.pth
