_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 54
                - 55
                - 105
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
ckpt:
    value: None
data:
    value:
        data_dir: ./data
        max_sequence_length: 5
        test_file: jet/qg_jet_test_data.nc
        train_file: jet/qg_jet_train_data.nc
        val_file: jet/qg_jet_val_data.nc
log_epoch:
    value: 10
loss:
    value:
        alpha: 1
        beta: 0.1
lr_scheduler:
    value:
        decay: 10000
        final_lr: 1e-05
        lr: 0.0001
        warmup: 500
model:
    value:
        block_size: 2
        conv_kwargs:
            padding: 1
            padding_mode: circular
        height: 256
        hidden_dims:
            - 64
            - 128
            - 64
        input_channels: 6
        kernel_size: 3
        latent_dim: 1024
        spatial_dim: 8
        width: 256
output_dir:
    value: model_outputs
training:
    value:
        batch_size: 15
        num_epochs: 1000
        patience: 1000
        use_checkpoint: true
