# configs/training/base.yaml
# base config for training

# training:
batch_size: 32
random_sequence_length: False
num_epochs: 1000
patience: 100
use_checkpoint: False
save_latest_every: 20
num_visual_batches: 1
precision: bfloat16
