# configs/loss/base.yaml
# base config for loss

# loss:
alpha: 1.0
beta: 0.5
loss_type: "l1"
physics_weight: 1.0
gamma_time: 1.0
gamma_space: 2.0
gamma_spectral: 0.01
ssim_weight: null # 0.1
re_weight: null # 0.0
stability_weight: null # null
weighting_type: "uniform"
sigma_blur: null
