# Top-level run configuration
output_dir: "model_outputs/128_inc_kl_1.0"
ckpt: null
log_epoch: 20

# Data configuration
data:
  dataset_type: "QGDatasetMultiSim" # "QGDatasetMultiSim" # "SingleSimOverfit"
  data_dir: "./data"
  train_file: "acdm/128_inc/train.nc"
  val_file: "acdm/128_inc/val.nc"
  test_file: "acdm/128_inc/test.nc"
  input_sequence_length: 2
  max_sequence_length: 10
  variables:
    v_x: 1
    v_y: 1
    p: 1
  static_variables:
    obstacle_mask: 1
  normalization:
    type: "MeanStdNormalizer"
    sim: 0
  quantile_range: [2.5, 97.5]

# Metric configuration
metric:
  mode: "SSIM"
  variable_mode: "all"
  variable_name: null

# Model architecture configuration
model:
  height: 64
  width: 128
  hidden_dims: [64, 128, 64]
  block_size: 2
  kernel_size: 3
  conv_kwargs:
    padding: 1
    padding_mode: "circular"
  latent_dim: 1024
  transformer:
    num_layers: 4
    nhead: 8
    ff_mult: 4
    max_len: 1000
    dropout: 0.1
  predict_re: True
  re_grad_enabled: False

# Training loop configuration
training:
  batch_size: 41
  random_sequence_length: False
  num_epochs: 1000
  patience: 100
  use_checkpoint: True
  save_latest_every: 1
  num_visual_batches: 1

# Learning rate scheduler configuration
lr_scheduler:
  lr: 1.0e-4
  warmup: 10
  decay: 990
  final_lr: 1.0e-5

# Loss function configuration
loss:
  alpha: 1.0
  beta: 1.0
  re_weight: 0.0
  weighting_type: "cosine"
  sigma_blur: null
