output_dir: "model_outputs"
data:
  data_dir: "./data"
  train_file: "acdm/128_tra/train.nc"
  val_file: "acdm/128_tra/val.nc"
  test_file: "acdm/128_tra/test.nc"
  input_sequence_length: 5
  max_sequence_length: 50
  normalization:
    type: "diff"
    sim: 0
metric:
  type: "SSIM"          # or "L2", "MI"
  variable_mode: "all"  # or "single"
  variable_name: ~      # if variable_mode is single => particular per dataset and variables
model:
  height: 64
  width: 128
  input_channels: 3 # rho, p, v only
  hidden_dims:
    - 64
    - 128
    - 64
  block_size: 2
  kernel_size: 3
  spatial_dim: 8
  conv_kwargs:
    padding: 1
    padding_mode: "circular"
  latent_dim: 1024 # sparial_dimË†2 * koopman latent dim
training:
  batch_size: 40
  num_epochs: 1000
  patience: 1000
  use_checkpoint: True
lr_scheduler:
  lr: !!float 1e-4
  warmup: 500
  decay: 10000
  final_lr: !!float 1e-5
loss:
  alpha: 1.0
  beta: 0.1
  weighting_type: cosine
  sigma_blur: ~

ckpt: ~
log_epoch: 10 # logging results every epoch
