output_dir: "model_outputs"
data:
  data_dir: "./data"
  train_file: "jet/qg_jet_train_data.nc"
  val_file: "jet/qg_jet_val_data.nc"
  test_file: "jet/qg_jet_test_data.nc"
  max_sequence_length: 5
model:
  height: 256
  width: 256
  input_channels: 6
  hidden_dims:
    - 64
    - 128
    - 64
  block_size: 2
  kernel_size: 3
  spatial_dim: 8
  conv_kwargs:
    padding: 1
    padding_mode: "circular"
  latent_dim: 1024 # sparial_dimË†2 * koopman latent dim
training:
  batch_size: 15
  num_epochs: 1000
  patience: 1000
  use_checkpoint: True
lr_scheduler:
  lr: !!float 1e-4
  warmup: 500
  decay: 10000
  final_lr: !!float 1e-5
loss:
  alpha: 1.0
  beta: 0.1

ckpt: null
log_epoch: 10 # logging results every epoch
