output_dir: "model_outputs"
data:
  data_dir: "./data"
  # train_file: "jet/qg_jet_train_data_clean.nc"
  train_file: "jet/qg_jet_train_data_clean.nc"
  val_file: "jet/qg_jet_val_data.nc"
  test_file: "jet/qg_jet_test_data.nc"
  max_sequence_length: 5  # Maximum sequence length
model:
  height: 256
  width: 256
  input_channels: 6
  hidden_dims:
    - 64
    - 128
    - 64
  block_size: 2
  kernel_size: 3
  spatial_dim: 8
  conv_kwargs:
    padding: 1
    padding_mode: "circular"
  latent_dim: 2048 # sparial_dimË†2 * koopman latent dim
training:
  batch_size: 3
  learning_rate: 0.0001
  num_epochs: 100
  patience: 10
  use_checkpoint: True
loss:
  alpha: 1.0
  beta: 0.1
