output_dir: "model_outputs"
data:
  data_dir: "./data"
  train_file: "jet/qg_jet_train_data.nc"
  val_file: "jet/qg_jet_val_data.nc"
  test_file: "jet/qg_jet_test_data.nc"
  max_sequence_length: 10  # Maximum sequence length
model:
  encoder:
    input_channels: 6
    hidden_dims:
      - 64
      - 128
      - 64
    block_size: 2
    kernel_size: 3
    spatial_dim: 8
    conv_kwargs:
      padding: 1
      padding_mode: "circular"
  decoder:
    input_channels: 6
    hidden_dims:
      - 64
      - 128
      - 64
    block_size: 2
    kernel_size: 3
    spatial_dim: 8
    conv_kwargs:
      padding: 1
      padding_mode: "circular"
  koopman_operator:
    latent_dim: 32
    spatial_dim: 8
  latent_dim: 2048 # sparial_dimË†2 * koopman latent dim
training:
  batch_size: 128
  learning_rate: 0.001
  num_epochs: 100
  patience: 10
loss:
  alpha: 1.0